name: "girssa"
author: "nobe4"
description: "Github RSS Action"

inputs:
  noop:
    description: "Run in no-operation mode, will not touch the github API."
    required: false
    default: false

  repository:
    description: The GitHub repository to store issues in, must be of format <owner>/<name>.
    required: false
    default: ${{ github.repository }}

  sources:
    description: "List of the RSS feeds to use, in JSON."
    required: false
    default: "sources.json"

  token:
    description: The GitHub token used to create an authenticated client.
    required: false
    default: ${{ github.token }}

outputs:
  count:
    description: "Count of processed items"

runs:
  using: "node16"
  main: "dist/index.js"
