name: "coverage"

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm clean-install
      - run: npm run coverage
