name: "units-test"

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm clean-install
      - run: npm test
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          noop: true
          token: faketoken
          repository: nobe4/girssa
